## LEARNING FROM CHAI AND CODE

In [1]:
import numpy as np

In [2]:
# arr_2D = np.array([1,2,3,4],[5,6,7,8]) #Will give error as the whole elements should be inside a single '[]'
arr_2D = np.array([[1,2,3,4],[5,6,7,8]]) #Now no error
arr_2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
#Multiplication in array
mul = np.array([1,2,3])
print("Multiplication of array element : ",mul * 2)

Multiplication of array element :  [2 4 6]


#### CHECK OPERATION TIME OF LIST AND ARRAY

In [ ]:

import time

start = time.time()
py_list = [i*2 for i in range(100000)]
end1 = time.time() - start

start2 = time.time()
py_arr = np.arange(100000) * 2
end2 = time.time() - start2
print("List operation time : ", end1)
print("Array operation time : ", end2)

List operation time :  0.006118059158325195
Array operation time :  0.0004589557647705078


### CREATING ARRAY FROM SCRATCH

In [ ]:
zeroes = np.zeros((3,5)) #all value 0
print(zeroes)

ones = np.ones((4,3))   #all value 1
print(ones)

full = np.full((2,2), 3) #all value constant [3]
print(full)

random = np.random.random((2,4)) # assign value randomly between 0 to 1 (decimal)
print(random)

sequence = np.arange(0,10, 2)  # assign values from a range 
print(sequence)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3 3]
 [3 3]]
[[0.4990728  0.55117621 0.37803532 0.12719255]
 [0.36544172 0.33806541 0.97725606 0.22520193]]
[0 2 4 6 8]


### Vector Matrix and Tensor

In [ ]:
vector = np.array([1,2,3]) # 1 Dimensional
print("Vector : ",vector)

matrix = np.array([[1,2,3],  # 2 Dimensional
                   [4,5,6]])
print("Matrix : \n", matrix)

tensor = np .array([[[1,2],[3,4]],  # 3 Dimensional or more 
                    [[5,6],[7,8]],
                    [[9,10],[11,12]]])
print("Tensor : \n", tensor)

Vector :  [1 2 3]
Matrix : 
 [[1 2 3]
 [4 5 6]]
Tensor : 
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


### Array properties

In [ ]:
arr = np.array([[1,2,3],        #basic array 2D
                [4,5,6]])

print ("Shape: ", arr.shape)   # gives rows and columns
print ("Size: ", arr.size)   # gives number of elements
print ("Dimension: ", arr.ndim)   # gives number of dimension
print("Datatype: ", arr.dtype)    # every integer bits memory given (datatype)


Shape:  (2, 3)
Size:  6
Dimension:  2
Datatype:  int64


### array reshaping


In [3]:
arr = np.arange(12)
print('Original array : ', arr)

reshape = arr.reshape((3,4))
print('Reshaped array : \n', reshape)

flatten = reshape.flatten()
print('Flattened array : ', flatten)

# returns original array view, not copy
raveled = flatten.ravel
print('Raveled(Original) array : ', raveled)

#transpose
transpose = reshape.T
print("Transposed array : \n", transpose)

Original array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array :  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled(Original) array :  <built-in method ravel of numpy.ndarray object at 0x1079de2d0>
Transposed array : 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
