### Numpy Array Operation

In [5]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print('Original array : ', arr)

print("Basic slicing : ", arr[2:7])
print("With steps : ", arr[1:8:2])

print("Negative indeing : ", arr[-3])

Original array :  [1 2 3 4 5 6 7 8 9]
Basic slicing :  [3 4 5 6 7]
With steps :  [2 4 6 8]
Negative indeing :  7


In [6]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print("Specific element : ", arr_2d[1,1])
print("entire row ; ", arr_2d[1])
print("entire col ; ", arr_2d[:, 2])

Specific element :  5
entire row ;  [4 5 6]
entire col ;  [3 6 9]


### Sorting

In [ ]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array : ", np.sort(unsorted))

unsorted_2d_arr = np.array([[3,1],[1,2],[2,3]])
print("Sorting of 2D by column: \n",np.sort(unsorted_2d_arr, axis=0))
print("Sorting of 2D by row: \n",np.sort(unsorted_2d_arr, axis=1))


Sorted array :  [1 1 2 3 4 5 6 9]
Sorting of 2D by column: 
 [[1 1]
 [2 2]
 [3 3]]
Sorting of 2D by row: 
 [[1 3]
 [1 2]
 [2 3]]


### Filter

In [14]:
numbers = np.arange(1, 11)
print(numbers)

even_numbers = numbers [numbers % 2 == 0]
print(even_numbers)

odd_numbers = numbers [numbers % 2 != 0]
print(odd_numbers)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[1 3 5 7 9]


### Filter with mask

In [16]:
mask =  numbers > 5
print("Numbers greater than 5 are : ", numbers[mask])

Numbers greater than 5 are :  [ 6  7  8  9 10]



### Fancy indexing vs np.where()

In [18]:
indices = [2,4,6] 
print(numbers[indices]) #uses indices as index value and print corresponding element

where_result = np.where(numbers > 5)
print("Numbers greater than 5 : ", numbers[where_result]) 

[3 5 7]
Numbers greater than 5 :  [ 6  7  8  9 10]


In [ ]:
condition_array = np.where(numbers > 3, numbers*3, numbers)
# np.where(condition, if True return value, if False return value)

print("Condition array : ", condition_array)
#numbers greater than 3 are multiplied by 3 rest as usual

Condition array :  [ 1  2  3 12 15 18 21 24 27 30]


### Adding and removing data

In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

add = arr1 + arr2 # this will add the values
print("Element added : ",add)

combined = np.concatenate((arr1,arr2))
print("Array merged : ", combined)

Element added :  [5 7 9]
Array merged :  [1 2 3 4 5 6]


### array compatibility

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6,4])
c = np.array([7,8,9])

print("Compatibility shape : ", a.shape == b.shape)



Compatibility shape :  False


### vstack and hstack

In [ ]:
#adding a row to 2D array (vstack)

original_arr = np.array([[1,2],[3,4]])
print("Original array : \n", original_arr)
new_row = np.array([[5,6]]) #this should also be 2D

with_new_row = np.vstack((original_arr, new_row))
print("With new row : \n", with_new_row)



Original array : 
 [[1 2]
 [3 4]]
With new row : 
 [[1 2]
 [3 4]
 [5 6]]


In [8]:
#adding a column to 2D array (hstack)

original_arr = np.array([[1,2],[3,4]])
print("Original array : \n", original_arr)
new_col = np.array([[5],[6]]) #these are column element to add

with_new_col = np.hstack((original_arr, new_col))
print("With new col : \n", with_new_col)

Original array : 
 [[1 2]
 [3 4]]
With new col : 
 [[1 2 5]
 [3 4 6]]


### Deletion in array

In [11]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)  #this will return array after deleting not the element deleted

print("New array after delete : ", deleted)

New array after delete :  [1 2 4 5]
